### ISSUE TITLE
API method blob returns base64

### ISSUE THREAD

**Issue by simare** [wemakecustom/gitlab-composer#24]
Hello, 
we are using gitlab in version 8.15.4 and Repository::blob api call returns an base64 encoded string instead of the file content.
So building package.json is not longer working.
I hope I did not overlook something obvious.

Best,
Ramon

**Comment by lemoinem** [comment]
Hello,

Thanks for reporting the issue. unfortunately, we don't really have the time to actively maintain this package.

However, if you were able to submit a PR, I would review it as quickly as possible.

**Comment by lemoinem** [comment]
Please confirm the merge of #25 did solve this issue.
